[package]
name = "rust_millionaires_problem"
version = "0.1.0"
authors = ["Dylan <dylanhrebenach@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
